Repository FallingColors/HexMod, pull requests merged in 2023-12, with the labels that each got.

#539 Make Operators capable of returning OperationResult
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/engine/ArithmeticEngine.java
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/operator/Operator.java
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/operator/Operator.kt
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/operator/OperatorBasic.kt
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/operator/OperatorBinary.java
  Common/src/main/java/at/petrak/hexcasting/api/casting/arithmetic/operator/OperatorUnary.java
  Common/src/main/java/at/petrak/hexcasting/api/casting/castables/OperationAction.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/BitwiseSetArithmetic.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/ListArithmetic.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/ListSetArithmetic.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/OperatorLog.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorAppend.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorIndex.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorIndexOf.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorRemove.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorReplace.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorSlice.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorUnCons.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorUnappend.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/list/OperatorUnique.kt
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/vec/OperatorPack.java
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/vec/OperatorUnpack.java
  Common/src/main/java/at/petrak/hexcasting/common/casting/arithmetic/operator/vec/OperatorVec3Delegating.java
Labels: 1.20

#559 Fix forge crashes on death
  Forge/src/main/java/at/petrak/hexcasting/forge/cap/adimpl/CapClientCastingStack.java
  Forge/src/main/java/at/petrak/hexcasting/forge/xplat/ForgeClientXplatImpl.java
Labels: forge, 1.20

#560 Fail Jenkins pipeline if datagen needs to be run
  Forge/build.gradle
  Forge/gradle.properties
  Jenkinsfile
  build.gradle
  gradle.properties
Labels: 1.20, needs reviewer

#555 Bring texture-based pattern rendering to 1.20
  Common/src/main/java/at/petrak/hexcasting/client/entity/WallScrollRenderer.java
  Common/src/main/java/at/petrak/hexcasting/client/render/HexPatternPoints.java
  Common/src/main/java/at/petrak/hexcasting/client/render/PatternTextureManager.java
  Common/src/main/java/at/petrak/hexcasting/client/render/be/BlockEntityAkashicBookshelfRenderer.java
  Common/src/main/java/at/petrak/hexcasting/client/render/be/BlockEntitySlateRenderer.java
  Common/src/main/java/at/petrak/hexcasting/common/blocks/akashic/BlockEntityAkashicBookshelf.java
  Common/src/main/java/at/petrak/hexcasting/common/blocks/circles/BlockEntitySlate.java
  Common/src/main/java/at/petrak/hexcasting/common/command/PatternTexturesCommand.java
  Common/src/main/java/at/petrak/hexcasting/common/entities/EntityWallScroll.java
  Common/src/main/java/at/petrak/hexcasting/common/lib/HexCommands.java
Labels: 1.20
